import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { api, send } from './api';
import { Badge, Empty, ErrorMessage, JsonView, Section } from './common';
import { columns, conditionValue, format, timestamp } from './model';
import type { AlertRule, Condition, Data, Envelope, Snapshot } from './types';
const operators=['==','!=','>','>=','<','<=','IN','NOT IN','BETWEEN','contains','changed','changed_to','crosses_above','crosses_below'];
const leaf=():Condition=>({field:'avg_setup',op:'>=',value:70});
const emptyRule=():AlertRule=>({name:'',enabled:false,conditions:{op:'AND',conditions:[leaf()]},mode:'confirmed',frequency:'once_per_bar',cooldown_seconds:60,template:'{symbol} · {timeframe} · {direction}\nACTION: {action}\nAVG SETUP: {avg_setup}\nFormation: {formation} · Execution: {execution}\nGeometry: {geometry} · Context: {context}\nLevel: {level} · Approach: {approach}\nMAE: {mae} · Exhaustion: {exhaustion} · BTC Shock: {btc_shock}\nCandidate: {candidate_path} · Trigger: {trigger_path}\nSL: {sl} · T1: {t1} · R:R: {rr}\nBlockers: {blockers}'});
function ConditionLeaf({node,onChange,onDelete}:{node:Condition;onChange:(value:Condition)=>void;onDelete:()=>void}){
 const [raw,setRaw]=useState(()=>Array.isArray(node.value)?JSON.stringify(node.value):String(node.value??''));
 return <div className="condition"><input aria-label="Метрика" list="alert-fields" value={node.field??''} onChange={e=>onChange({...node,field:e.target.value})}/><select aria-label="Оператор" value={node.op} onChange={e=>onChange({...node,op:e.target.value,value:conditionValue(e.target.value,raw)})}>{operators.map(op=><option key={op}>{op}</option>)}</select>{node.op!=='changed'&&<input aria-label="Значение условия" placeholder={['IN','NOT IN','BETWEEN'].includes(node.op)?'70, 90 или [70, 90]':'Значение'} value={raw} onChange={e=>{setRaw(e.target.value);onChange({...node,value:conditionValue(node.op,e.target.value)});}}/>}<button type="button" className="icon-button danger" aria-label="Удалить условие" onClick={onDelete}>×</button></div>;
}
function ConditionGroup({node,onChange,onDelete,depth=0}:{node:Condition;onChange:(value:Condition)=>void;onDelete?:()=>void;depth?:number}){
 if(!node.conditions)return <ConditionLeaf node={node} onChange={onChange} onDelete={()=>onDelete?.()}/>;
 const children=node.conditions;
 return <fieldset className="condition-group"><legend><select aria-label="Логическая группа" value={node.op} onChange={e=>onChange({...node,op:e.target.value,conditions:e.target.value==='NOT'?children.slice(0,1):children})}>{['AND','OR','NOT'].map(op=><option key={op}>{op}</option>)}</select><span>{node.op==='AND'?'Все условия':node.op==='OR'?'Хотя бы одно':'Отрицание условия'}</span>{onDelete&&<button type="button" className="icon-button danger" aria-label="Удалить группу" onClick={onDelete}>×</button>}</legend>
 {children.map((child,index)=><ConditionGroup key={index} node={child} depth={depth+1} onChange={value=>onChange({...node,conditions:children.map((x,i)=>i===index?value:x)})} onDelete={()=>onChange({...node,conditions:children.filter((_,i)=>i!==index)})}/>)}
 {(node.op!=='NOT'||children.length===0)&&<div className="group-actions"><button type="button" onClick={()=>onChange({...node,conditions:[...children,leaf()]})}>+ Условие</button>{depth<8&&<button type="button" onClick={()=>onChange({...node,conditions:[...children,{op:'AND',conditions:[leaf()]}]})}>+ Группа</button>}</div>}</fieldset>;
}
export function Alerts(){
 const cache=useQueryClient();const rules=useQuery({queryKey:['rules'],queryFn:()=>api<Envelope<AlertRule>>('/api/alerts/rules')});
 const deliveries=useQuery({queryKey:['deliveries'],queryFn:()=>api<Envelope<Data>>('/api/alerts/deliveries?limit=100'),refetchInterval:15000});
 const [rule,setRule]=useState<AlertRule>(emptyRule),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),[matches,setMatches]=useState<Envelope<Snapshot>|null>(null),[telegramResult,setTelegramResult]=useState<unknown>();
 const update=<K extends keyof AlertRule>(key:K,value:AlertRule[K])=>setRule(old=>({...old,[key]:value}));
 async function perform(job:()=>Promise<void>){setBusy(true);setError(undefined);setNotice('');try{await job();}catch(e){setError(e);}finally{setBusy(false);}}
 function edit(next:AlertRule){setRule(structuredClone(next));setRevision(x=>x+1);setMatches(null);setNotice('');}
 return <><div className="page-heading"><div><p className="eyebrow">RULE ENGINE · TELEGRAM</p><h1>Alerts</h1><p>Вложенные условия, crossings и контролируемая частота отправки</p></div><button onClick={()=>edit(emptyRule())}>+ Новое правило</button></div><ErrorMessage error={error??rules.error}/>{notice&&<div role="status" className="success">{notice}</div>}
 <div className="alerts-grid"><Section title="Правила">{!rules.data?.items.length?<Empty>Правил пока нет. Создайте первое правило справа.</Empty>:rules.data.items.map(item=><div className={`rule-card ${item.id===rule.id?'active':''}`} key={item.id}><button className="rule-name" onClick={()=>edit(item)}>{item.name}</button><Badge tone={item.enabled?'good':'neutral'}>{item.enabled?'ON':'OFF'}</Badge><small>{item.mode} · {item.frequency}</small><div><button disabled={busy} onClick={()=>void perform(async()=>{await send(`/api/alerts/rules/${item.id}`,'PUT',{...item,enabled:!item.enabled});await cache.invalidateQueries({queryKey:['rules']});if(rule.id===item.id)update('enabled',!item.enabled);})}>{item.enabled?'Выключить':'Включить'}</button><button className="danger" disabled={busy} onClick={()=>{if(window.confirm(`Удалить правило «${item.name}»?`))void perform(async()=>{await send(`/api/alerts/rules/${item.id}`,'DELETE');await cache.invalidateQueries({queryKey:['rules']});if(rule.id===item.id)edit(emptyRule());});}}>Удалить</button></div></div>)}</Section>
 <Section title={rule.id?'Редактирование правила':'Новое правило'}><form onSubmit={e=>{e.preventDefault();void perform(async()=>{const saved=await send<AlertRule>(`/api/alerts/rules${rule.id?'/'+rule.id:''}`,rule.id?'PUT':'POST',rule);edit(saved);await cache.invalidateQueries({queryKey:['rules']});setNotice('Правило сохранено.');});}}><div className="form-grid"><label>Название<input required value={rule.name} onChange={e=>update('name',e.target.value)} placeholder="Например: LONG · quality ≥ 70"/></label><label className="inline"><input type="checkbox" checked={rule.enabled} onChange={e=>update('enabled',e.target.checked)}/>Правило включено</label></div>
 <datalist id="alert-fields">{[...columns.map(x=>x[0]),'event','signals','blockers','risk_path','setup_generation_id'].map(field=><option key={field} value={field}/>)}</datalist>
 <ConditionGroup key={revision} node={rule.conditions} onChange={value=>update('conditions',value)}/><p className="subtle">Доступны любые исходные поля, включая metrics.имяПеременной. IN / NOT IN / BETWEEN: список через запятую или JSON. changed и crosses сравнивает backend с предыдущим состоянием.</p>
 <div className="form-grid"><label>Режим<select value={rule.mode} onChange={e=>update('mode',e.target.value)}><option value="confirmed">Только confirmed close</option><option value="realtime">Realtime</option></select></label><label>Частота<select value={rule.frequency} onChange={e=>update('frequency',e.target.value)}><option value="once_per_bar">Один раз за бар</option><option value="once_per_generation">Один раз за setup generation</option><option value="first_occurrence">Первое совпадение</option><option value="repeat">Повторять, пока true</option></select></label><label>Cooldown, секунды<input type="number" required min="0" value={rule.cooldown_seconds} onChange={e=>update('cooldown_seconds',Number(e.target.value))}/></label></div>
 <label>Шаблон Telegram<textarea rows={9} value={rule.template} onChange={e=>update('template',e.target.value)}/></label><p className="subtle">Поля в фигурных скобках: {'{symbol}, {action}, {avg_setup}, {sl}, {t1}, {rr}'}. Ссылка на detail добавляется сервером.</p>
 <div className="toolbar"><button className="primary" disabled={busy} type="submit">{busy?'Выполняется…':'Сохранить правило'}</button><button type="button" disabled={busy} onClick={()=>void perform(async()=>{setMatches(await send<Envelope<Snapshot>>('/api/alerts/rules/test','POST',{conditions:rule.conditions}));})}>Проверить текущие setups</button></div></form>
 {matches&&<div className="match-results"><h3>Совпадения сейчас: {matches.total??matches.items.length}</h3>{matches.items.length?matches.items.map((item,i)=><Link key={i} to={`/setups/${item.exchange}/${item.symbol}/${item.timeframe}`}>{item.symbol} · {item.timeframe} · {format(item.action)}</Link>):<p>Текущие состояния не соответствуют условиям. Crossings требуют предыдущего состояния.</p>}</div>}
 <details><summary>JSON условия</summary><JsonView data={rule.conditions}/></details></Section></div>
 <Section title="Telegram connection"><p>Отправить одно тестовое сообщение в чат, настроенный на сервере.</p><button disabled={busy} onClick={()=>void perform(async()=>{setTelegramResult(await send('/api/alerts/test-telegram','POST',{}));setNotice('Запрос тестовой отправки выполнен. Проверьте результат ниже.');await cache.invalidateQueries({queryKey:['deliveries']});})}>Отправить test Telegram</button>{telegramResult!==undefined&&<JsonView data={telegramResult}/>}</Section>
 <Section title="История срабатываний / доставки"><ErrorMessage error={deliveries.error}/>{!deliveries.data?.items.length?<Empty>История отправок пуста.</Empty>:<div className="table-scroll"><table><thead><tr><th>UTC</th><th>Правило</th><th>Symbol / TF</th><th>Статус</th><th>Сообщение / ошибка</th></tr></thead><tbody>{deliveries.data.items.map((item,i)=><tr key={String(item.id??i)}><td>{timestamp(item.created_at??item.event_time)}</td><td>{format(item.rule_name??item.rule_id)}</td><td>{format(item.symbol)} / {format(item.timeframe)}</td><td>{format(item.status)}</td><td className="wrap">{format(item.error??item.message??item.payload)}</td></tr>)}</tbody></table></div>}</Section></>;
}
