import {useDisplayTime} from './Timezone';
import { useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { api, send } from './api';
import { Badge, Empty, ErrorMessage, JsonView, Section } from './common';
import { format } from './model';
import { ConditionLeaf } from './ConditionLeaf';
import { copyRuleInput } from './alertRuleCopy';
import type { FieldCatalog } from './ruleFields';
import type { AlertRule, Condition, Data, Envelope, Snapshot } from './types';
const leaf=():Condition=>({field:'avg_setup',op:'>=',value:70});
const ruleInput=(item:AlertRule)=>({strategy:item.strategy??'BROKE_SETUPS',name:item.name,enabled:item.enabled,conditions:item.conditions,mode:item.mode,frequency:item.frequency,cooldown_seconds:item.cooldown_seconds,template:item.template});
const emptyRule=():AlertRule=>({strategy:'BROKE_SETUPS',name:'',enabled:false,conditions:{op:'AND',conditions:[{field:'timeframe',op:'IN',value:['30','5']},leaf()]},mode:'confirmed',frequency:'once_per_bar',cooldown_seconds:60,template:'{symbol} · {timeframe} · {direction}\nACTION: {action}\nAVG SETUP: {avg_setup}\nFormation: {formation} · Execution: {execution}\nGeometry: {geometry} · Context: {context}\nLevel: {level} · Approach: {approach}\nMAE: {mae} · Exhaustion: {exhaustion} · BTC Shock: {btc_shock}\nCandidate: {candidate_path} · Trigger: {trigger_path}\nSL: {sl} · T1: {t1} · R:R: {rr}\nBlockers: {blockers}\n{detail_url}'});
function ConditionGroup({node,catalog,onChange,onDelete,depth=0}:{node:Condition;catalog:FieldCatalog;onChange:(value:Condition)=>void;onDelete?:()=>void;depth?:number}){
 if(!node.conditions)return <ConditionLeaf node={node} catalog={catalog} onChange={onChange} onDelete={()=>onDelete?.()}/>;
 const children=node.conditions;
 return <fieldset className="condition-group"><legend><select aria-label="Логическая группа" value={node.op} onChange={e=>onChange({...node,op:e.target.value,conditions:e.target.value==='NOT'?children.slice(0,1):children})}>{['AND','OR','NOT'].map(op=><option key={op}>{op}</option>)}</select><span>{node.op==='AND'?'Все условия':node.op==='OR'?'Хотя бы одно':'Отрицание условия'}</span>{onDelete&&<button type="button" className="icon-button danger" aria-label="Удалить группу" onClick={onDelete}>×</button>}</legend>
 {children.map((child,index)=><ConditionGroup key={index} node={child} catalog={catalog} depth={depth+1} onChange={value=>onChange({...node,conditions:children.map((x,i)=>i===index?value:x)})} onDelete={()=>onChange({...node,conditions:children.filter((_,i)=>i!==index)})}/>)}
 {(node.op!=='NOT'||children.length===0)&&<div className="group-actions"><button type="button" onClick={()=>onChange({...node,conditions:[...children,leaf()]})}>+ Условие</button>{depth<8&&<button type="button" onClick={()=>onChange({...node,conditions:[...children,{op:'AND',conditions:[leaf()]}]})}>+ Группа</button>}</div>}</fieldset>;
}
export function Alerts(){
 const importFile=useRef<HTMLInputElement>(null);
 const {timestamp,label}=useDisplayTime();
 const fields=useQuery({queryKey:['alert-fields'],queryFn:()=>api<FieldCatalog>('/api/alerts/fields')});
 const cache=useQueryClient();const rules=useQuery({queryKey:['rules'],queryFn:()=>api<Envelope<AlertRule>>('/api/alerts/rules')});
 const deliveries=useQuery({queryKey:['deliveries'],queryFn:()=>api<Envelope<Data>>('/api/alerts/deliveries?limit=100'),refetchInterval:15000});
 const tradingview=useQuery({queryKey:['tradingview-alerts'],queryFn:()=>api<Envelope<Data>>('/api/tradingview/alerts?limit=50'),refetchInterval:15000});
 const [rule,setRule]=useState<AlertRule>(emptyRule),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),[matches,setMatches]=useState<Envelope<Snapshot>|null>(null),[telegramResult,setTelegramResult]=useState<unknown>();
 const update=<K extends keyof AlertRule>(key:K,value:AlertRule[K])=>setRule(old=>({...old,[key]:value}));
 async function perform(job:()=>Promise<void>){setBusy(true);setError(undefined);setNotice('');try{await job();}catch(e){setError(e);}finally{setBusy(false);}}
 function edit(next:AlertRule){setRule(structuredClone(next));setRevision(x=>x+1);setMatches(null);setNotice('');}
 async function exportRules(){
  const data=await api('/api/alerts/rules/export');
  const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));
  const link=document.createElement('a');link.href=url;link.download=`brokeweb-alert-rules-${new Date().toISOString().slice(0,10)}.json`;link.click();
  setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Сохранённые правила экспортированы. Несохранённые изменения редактора в файл не входят.');
 }
 async function importRules(file:File){
  if(file.size>1024*1024)throw new Error('Файл правил должен быть не больше 1 МБ.');
  const data:unknown=JSON.parse(await file.text());
  const result=await send<Envelope<AlertRule>>('/api/alerts/rules/import','POST',data);
  await cache.invalidateQueries({queryKey:['rules']});setNotice(`Добавлено правил: ${result.total}. Существующие правила сохранены.`);
 }
 async function copySelectedRule(){
  const saved=await send<AlertRule>('/api/alerts/rules','POST',copyRuleInput(rule));
  edit(saved);await cache.invalidateQueries({queryKey:['rules']});setNotice('Копия правила создана и сохранена.');
 }
 return <><div className="page-heading"><div><p className="eyebrow">RULE ENGINE · TELEGRAM</p><h1>Alerts</h1><p>BROKE · контролируемая частота отправки</p></div><div className="toolbar"><button disabled={busy} onClick={()=>edit(emptyRule())}>+ Новое правило</button><button disabled={busy||!rule.id} title={rule.id?'Создать копию выбранного правила':'Выберите правило для копирования'} onClick={()=>void perform(copySelectedRule)}>Скопировать правило</button></div></div><ErrorMessage error={error??rules.error??fields.error}/>{notice&&<div role="status" className="success">{notice}</div>}
 <div className="toolbar"><button disabled={busy||!rules.data?.items.length} onClick={()=>void perform(exportRules)}>Сохранить правила в файл</button><button disabled={busy} onClick={()=>importFile.current?.click()}>Импортировать из файла</button><input ref={importFile} type="file" accept=".json,application/json" hidden aria-label="Файл правил" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void perform(()=>importRules(file));}}/><span className="subtle">JSON · импорт добавляет правила и сохраняет их состояние ON/OFF</span></div>
 <div className="alerts-grid"><Section title="Правила">{!rules.data?.items.length?<Empty>Правил пока нет. Создайте первое правило справа.</Empty>:rules.data.items.map(item=><div className={`rule-card ${item.id===rule.id?'active':''}`} key={item.id}><button className="rule-name" onClick={()=>edit(item)}>{item.name}</button><Badge tone={item.enabled?'good':'neutral'}>{item.enabled?'ON':'OFF'}</Badge><small>{item.mode} · {item.frequency}</small><div><button disabled={busy} onClick={()=>void perform(async()=>{await send(`/api/alerts/rules/${item.id}`,'PUT',{...ruleInput(item),enabled:!item.enabled});await cache.invalidateQueries({queryKey:['rules']});if(rule.id===item.id)update('enabled',!item.enabled);})}>{item.enabled?'Выключить':'Включить'}</button><button className="danger" disabled={busy} onClick={()=>{if(window.confirm(`Удалить правило «${item.name}»?`))void perform(async()=>{await send(`/api/alerts/rules/${item.id}`,'DELETE');await cache.invalidateQueries({queryKey:['rules']});if(rule.id===item.id)edit(emptyRule());});}}>Удалить</button></div></div>)}</Section>
 <Section title={rule.id?'Редактирование правила':'Новое правило'}><form onSubmit={e=>{e.preventDefault();void perform(async()=>{const saved=await send<AlertRule>(`/api/alerts/rules${rule.id?'/'+rule.id:''}`,rule.id?'PUT':'POST',ruleInput(rule));edit(saved);await cache.invalidateQueries({queryKey:['rules']});setNotice('Правило сохранено.');});}}><div className="form-grid"><label>Название<input required value={rule.name} onChange={e=>update('name',e.target.value)} placeholder="Например: LONG · quality ≥ 70"/></label><label className="inline"><input type="checkbox" checked={rule.enabled} onChange={e=>update('enabled',e.target.checked)}/>Правило включено</label></div>

 {fields.data?<ConditionGroup key={revision} catalog={fields.data} node={rule.conditions} onChange={value=>update('conditions',value)}/>:<p>Загрузка типов полей…</p>}<p className="subtle">== выбирает одно значение; IN / NOT IN — несколько. Для signals и blockers: contains — одно, contains_any / contains_all — несколько. Числа без кавычек и %, текст без кавычек. changed не требует значения.</p>
 <div className="form-grid"><label>Режим<select value={rule.mode} onChange={e=>update('mode',e.target.value)}><option value="confirmed">Только confirmed close</option><option value="realtime">Realtime</option></select></label><label>Частота<select value={rule.frequency} onChange={e=>update('frequency',e.target.value)}><option value="once_per_bar">Один раз за бар</option><option value="once_per_generation">Один раз за setup generation</option><option value="first_occurrence">Первое совпадение</option><option value="repeat">Повторять, пока true</option></select></label><label>Cooldown, секунды<input type="number" required min="0" value={rule.cooldown_seconds} onChange={e=>update('cooldown_seconds',Number(e.target.value))}/></label></div>
 <label>Шаблон Telegram<textarea rows={9} value={rule.template} onChange={e=>update('template',e.target.value)}/></label><p className="subtle">Поля в фигурных скобках: {'{symbol}, {action}, {avg_setup}, {sl}, {t1}, {rr}'}. Для ссылки добавьте {'{detail_url}'}. Вложенные пути metrics.* в шаблоне не поддерживаются.</p>
 <div className="toolbar"><button className="primary" disabled={busy||!fields.data} type="submit">{busy?'Выполняется…':'Сохранить правило'}</button><button type="button" disabled={busy||!fields.data} onClick={()=>void perform(async()=>{setMatches(await send<Envelope<Snapshot>>('/api/alerts/rules/test','POST',{conditions:rule.conditions,strategy:rule.strategy??'BROKE_SETUPS'}));})}>Проверить текущие setups</button></div></form>
 {matches&&<div className="match-results"><h3>Совпадения сейчас: {matches.total??matches.items.length}</h3>{matches.items.length?matches.items.map((item,i)=><Link key={i} to={`/setups/${item.exchange}/${item.symbol}/${item.timeframe}`}>{item.symbol} · {item.timeframe} · {format(item.action)}</Link>):<p>Текущие состояния не соответствуют условиям. Crossings требуют предыдущего состояния.</p>}</div>}
 <details><summary>JSON условия</summary><JsonView data={rule.conditions}/></details></Section></div>
 <Section title="TradingView · входящие webhook"><p>Последние 50 сообщений TradingView · 5m / 30m. Хранение — 30 дней. <Link to="/parity">Проверка parity</Link></p><ErrorMessage error={tradingview.error}/>{!tradingview.data?.items.length?<Empty>Сигналы TradingView пока не получены.</Empty>:<div className="table-scroll"><table><thead><tr><th>Получено · {label}</th><th>Инструмент</th><th>Сигнал</th><th>Сообщение</th></tr></thead><tbody>{tradingview.data.items.map(item=><tr key={String(item.id)}><td>{timestamp(item.received_at)}</td><td>{format(item.exchange)}:{format(item.symbol)} · {format(item.timeframe)}</td><td>{format(item.name??item.parse_status)}{Boolean(item.parse_reason) && <small className="wrap">{format(item.parse_reason)}</small>}</td><td className="wrap">{format(item.raw_body)}</td></tr>)}</tbody></table></div>}</Section>
 <Section title="Telegram connection"><p>Отправить одно тестовое сообщение в чат, настроенный на сервере.</p><button disabled={busy} onClick={()=>void perform(async()=>{setTelegramResult(await send('/api/alerts/test-telegram','POST',{}));setNotice('Запрос тестовой отправки выполнен. Проверьте результат ниже.');await cache.invalidateQueries({queryKey:['deliveries']});})}>Отправить test Telegram</button>{telegramResult!==undefined&&<JsonView data={telegramResult}/>}</Section>
 <Section title="История срабатываний / доставки"><ErrorMessage error={deliveries.error}/>{!deliveries.data?.items.length?<Empty>История отправок пуста.</Empty>:<div className="table-scroll"><table><thead><tr><th>{label}</th><th>Правило</th><th>Symbol / TF</th><th>Статус</th><th>Сообщение / ошибка</th></tr></thead><tbody>{deliveries.data.items.map((item,i)=><tr key={String(item.id??i)}><td>{timestamp(item.created_at??item.event_time)}</td><td>{format(item.rule_name??item.rule_id)}</td><td>{format(item.symbol)} / {format(item.timeframe)}</td><td>{format(item.status)}</td><td className="wrap">{format(item.error??item.message??item.payload)}</td></tr>)}</tbody></table></div>}</Section></>;
}
