import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { api } from './api';
import { Badge, Empty, ErrorMessage, JsonView, Section, gateTone } from './common';
import { CandleChart, MetricChart } from './Charts';
import { format, formatField, timestamp, valueOf } from './model';
import type { Bar, Data, Envelope, PanelRow, Snapshot } from './types';
const panelFields=[['ACTION','action'],['BLOCKERS','blockers'],['Family / State','fsm'],['Direction / Path','direction'],['AVG SETUP','avg_setup'],['CONTINUATION','continuation'],['Formation Quality','formation'],['Execution Quality','execution'],['Geometry Quality','geometry'],['Exhaustion Risk','exhaustion'],['MAE Risk','mae'],['Hard Gates','hard_gates'],['Fresh Trigger','fresh_trigger'],['Candidate Path','candidate_path'],['Trigger Path','trigger_path'],['MATURED Entry','matured_entry'],['Pre-break Safety','preBreakSafetyAllowed'],['DOM / Tape Gate','entryReady'],['Level Quality','level'],['Trigger Zone','trigger_zone'],['Distance → level','distance'],['Approach Quality','approach'],['Structure','structure'],['MTF Trend Quality','mtf_trend'],['Dynamic Support','dynamicSupportQualityLong'],['HTF Base','htfBaseQualityLong'],['Broad Consolidation','broadConsolidationQualityLong'],['ATH / Open Sky','openSkyModeActive'],['Fixed-time In-Play','activityCheckCount'],['Context Quality','context'],['Estimated SL','sl'],['Forecast T1','t1'],['R:R → T1','rr'],['Target Freshness','target_freshness'],['ACTIVE Plan Health','active_plan_health'],['ADD-ON Gate','addon_gate'],['Research Mode','researchMode'],['Research WATCH ENTRY','researchWatchText'],['Research MATURED','researchMaturedText'],['Research PINE READY','researchPineText'],['Research BRONZE','researchBronzeText'],['Research STRONG','researchStrongText']];
const metricFields=[['avg_setup','AVG SETUP'],['formation','Formation'],['execution','Execution'],['geometry','Geometry'],['context','Context'],['mae','MAE'],['exhaustion','Exhaustion'],['level','Level'],['approach','Approach'],['btc_shock','BTC Shock'],['price','Price']];
const periods:Record<string,number>={'15m':900000,'1h':3600000,'6h':21600000,'24h':86400000,'7d':604800000};
export function Detail(){
 const {exchange='',symbol='',timeframe=''}=useParams();const [period,setPeriod]=useState('1h'),[from,setFrom]=useState(''),[until,setUntil]=useState(''),[end,setEnd]=useState(()=>Date.now());
 const base=`/api/setups/${encodeURIComponent(symbol)}/${encodeURIComponent(timeframe)}`,query=`exchange=${encodeURIComponent(exchange)}`;
 const customValid=period!=='custom'||Boolean(from&&until&&new Date(from)<new Date(until));
 const since=period==='custom'?new Date(from).valueOf():end-periods[period],to=period==='custom'?new Date(until).valueOf():end;
 const current=useQuery({queryKey:['setup',exchange,symbol,timeframe],queryFn:()=>api<Snapshot>(`${base}?${query}`),refetchInterval:10000});
 const bars=useQuery({queryKey:['bars',exchange,symbol,timeframe],queryFn:()=>api<Envelope<Bar>>(`${base}/bars?${query}&limit=1000`),refetchInterval:15000});
 const history=useQuery({queryKey:['history',exchange,symbol,timeframe,since,to],queryFn:()=>api<Envelope<Snapshot>>(`${base}/history?${query}&since=${since}&until=${to}&limit=10000`),enabled:customValid});
 const events=useQuery({queryKey:['events',exchange,symbol,timeframe,since,to],queryFn:()=>api<Envelope<Data>>(`${base}/events?${query}&since=${since}&until=${to}&limit=1000`),enabled:customValid,refetchInterval:15000});
 const snapshot=current.data;
 const rows:PanelRow[]=snapshot?.decision_panel?.length?snapshot.decision_panel:panelFields.map(([label,key],row)=>({row:row+1,label,value:snapshot?valueOf(snapshot,key):null,state:typeof snapshot?.gates?.[key]==='number'?snapshot.gates[key] as number:null}));
 return <><Link className="back" to="/setups">← Все setups</Link><div className="page-heading"><div><p className="eyebrow">{exchange} · {timeframe} · PERPETUAL</p><h1>{symbol} <span className="price">{format(snapshot?.price,8)}</span></h1><p>Обновлено: {timestamp(snapshot?.event_time)} · {snapshot?.confirmed?'Confirmed close':'Realtime / unconfirmed'}</p></div><Badge>{format(snapshot?.action)}</Badge></div><ErrorMessage error={current.error}/>
 <div className="detail-grid"><div><Section title="Price & structural zones"><ErrorMessage error={bars.error}/><CandleChart key={`${exchange}/${symbol}/${timeframe}`} bars={bars.data?.items??[]} snapshot={snapshot} events={events.data?.items??[]}/></Section>
 <Section title="История атрибутов" tools={<div className="segmented">{[...Object.keys(periods),'custom'].map(p=><button key={p} className={period===p?'selected':''} onClick={()=>{setPeriod(p);setEnd(Date.now());}}>{p}</button>)}<button onClick={()=>setEnd(Date.now())}>↻</button></div>}>
 {period==='custom'&&<div className="toolbar"><label>С (локальное время)<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>По<input type="datetime-local" value={until} onChange={e=>setUntil(e.target.value)}/></label>{!customValid&&<span className="warning">Задайте начало и конец периода.</span>}</div>}<ErrorMessage error={history.error}/><div className="metric-grid">{metricFields.map(([metric,label])=><MetricChart key={metric} metric={metric} label={label} items={history.data?.items??[]}/>)}</div></Section>
 <Section title="Timeline"><ErrorMessage error={events.error}/>{!events.data?.items.length?<Empty>За выбранный период событий нет.</Empty>:<div className="timeline">{[...events.data.items].reverse().map((event,i)=><article key={String(event.id??i)}><time>{timestamp(event.event_time??event.timestamp??event.created_at)}</time><strong>{format(event.event??event.kind??event.type??event.event_type??event.signal)}</strong><span>{format(event.action??event.to_state??event.message??(event.before!==undefined||event.after!==undefined?`${format(event.before)} → ${format(event.after)}`:event.payload))}</span></article>)}</div>}</Section></div>
 <Section title="Decision Panel · FULL"><table className="decision"><thead><tr><th>DECISION</th><th>VALUE</th><th>OK</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.row??i} title={row.note}><th>{row.label}</th><td className={gateTone(row.state)}>{formatField(panelFields.find(([label])=>label===row.label)?.[1]??'',row.value)}{row.note&&<small>{row.note}</small>}</td><td className={gateTone(row.state)}>{row.state===1?'✓':row.state===-1?'×':row.state===0?'·':'н/д'}</td></tr>)}</tbody></table></Section></div>
 <Section title="Воспроизводимость"><dl className="metadata">{['setup_generation_id','engine_version','pine_source_hash','parameter_set_id','parity_status','data_health','received_at'].map(key=><div key={key}><dt>{key}</dt><dd>{key==='received_at'?timestamp(snapshot?.[key]):format(snapshot?.[key])}</dd></div>)}</dl><details><summary>Все исходные метрики engine</summary><JsonView data={snapshot?.metrics??{}}/></details></Section></>;
}
