import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, send } from './api';
import { Empty, ErrorMessage, Section } from './common';
import { format } from './model';
import type { Data, Parameter, Parameters } from './types';
function ParameterInput({field,value,onChange}:{field:Parameter;value:unknown;onChange:(value:unknown)=>void}){
 if(field.options?.length)return <select value={String(value??'')} onChange={e=>onChange(field.options?.find(x=>String(x)===e.target.value)??e.target.value)}>{field.options.map(x=><option key={String(x)} value={String(x)}>{format(x)}</option>)}</select>;
 if(field.type==='bool')return <input type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked)}/>;
 if(['int','float'].includes(field.type))return <input type="number" required step={field.type==='int'?1:'any'} min={field.minval} max={field.maxval} value={typeof value==='number'?value:''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/>;
 return <input value={value==null?'':String(value)} onChange={e=>onChange(e.target.value)}/>;
}
function ParameterEditor({parameters}:{parameters:Parameters}){
 const cache=useQueryClient();const [values,setValues]=useState<Data>(parameters.values),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState('');
 const changed=parameters.schema.filter(field=>JSON.stringify(values[field.name])!==JSON.stringify(parameters.values[field.name]));
 const filtered=parameters.schema.filter(field=>`${field.name} ${field.title} ${field.group} ${field.tooltip}`.toLowerCase().includes(search.toLowerCase()));
 const groups=[...new Set(filtered.map(field=>field.group??'General'))];
 async function save(){setBusy(true);setError(undefined);try{const saved=await send<Parameters>('/api/parameters','PUT',{values});cache.setQueryData(['parameters'],saved);setNotice(`Сохранён parameter set ${saved.id}.`);}catch(e){setError(e);}finally{setBusy(false);}}
 return <form onSubmit={e=>{e.preventDefault();void save();}}><div className="toolbar sticky-toolbar"><input className="parameter-search" aria-label="Поиск параметров" placeholder="Поиск по названию, группе или пояснению…" value={search} onChange={e=>setSearch(e.target.value)}/><span>{filtered.length} / {parameters.schema.length} inputs</span><button disabled={busy||changed.length===0} className="primary">Сохранить версию ({changed.length})</button><button type="button" onClick={()=>{setValues({...parameters.values});setNotice('');}}>Отменить изменения</button></div><ErrorMessage error={error}/>{notice&&<div className="success" role="status">{notice}</div>}
 {groups.map(group=><details className="parameter-group" key={group} open={search?true:undefined}><summary>{group} <span>{filtered.filter(x=>(x.group??'General')===group).length}</span></summary><div className="parameters">{filtered.filter(x=>(x.group??'General')===group).map(field=><div className={`parameter ${changed.some(x=>x.name===field.name)?'modified':''}`} key={field.name}><label htmlFor={field.name}>{field.title||field.name}<code>{field.name}</code></label><div id={field.name}><ParameterInput field={field} value={values[field.name]??field.default} onChange={value=>setValues(old=>({...old,[field.name]:value}))}/></div><p>{field.tooltip||'Исходный input Pine Script.'}<small>Default: {format(field.default)}{field.minval!=null?` · min ${field.minval}`:''}{field.maxval!=null?` · max ${field.maxval}`:''}</small></p><button type="button" title="Вернуть Pine default" onClick={()=>setValues(old=>({...old,[field.name]:field.default}))}>↺</button></div>)}</div></details>)}
 {!groups.length&&<Empty>Параметры не найдены.</Empty>}<p className="subtle">Сохранение создаёт воспроизводимую версию параметров. Валидация ограничений выполняется сервером; расчётные значения на фронтенде не изменяются.</p></form>;
}
export function Settings(){
 const query=useQuery({queryKey:['parameters'],queryFn:()=>api<Parameters>('/api/parameters')});const runtime=useQuery({queryKey:['settings'],queryFn:()=>api<Data>('/api/settings')});
 const [interval,setIntervalValue]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState('');
 return <><div className="page-heading"><div><p className="eyebrow">PINE INPUTS · VERSIONED</p><h1>Settings</h1><p>Полный набор параметров исходного Pine. Текущая версия: <code>{query.data?.id??'н/д'}</code></p></div></div><Section title="Сохранение snapshots"><ErrorMessage error={runtime.error??error}/><form className="toolbar" onSubmit={e=>{e.preventDefault();setBusy(true);setError(undefined);void send('/api/settings','PUT',{snapshot_interval_sec:Number(interval??runtime.data?.snapshot_interval_sec??15)}).then(()=>{setNotice('Интервал snapshots сохранён.');return runtime.refetch();}).catch(setError).finally(()=>setBusy(false));}}><label>Интервал, секунды<input required type="number" min="1" step="1" value={interval??String(runtime.data?.snapshot_interval_sec??'')} onChange={e=>setIntervalValue(e.target.value)}/></label><button disabled={busy||!runtime.data}>Сохранить интервал</button><p className="subtle">Периодическая запись состояния всех атрибутов для истории и исследований.</p></form>{notice&&<p className="success">{notice}</p>}</Section><ErrorMessage error={query.error}/>{query.data?<ParameterEditor parameters={query.data}/>:<Empty>{query.isPending?'Загрузка схемы Pine inputs…':'Схема параметров недоступна.'}</Empty>}</>;
}
