import {useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useSearchParams} from 'react-router-dom';
import {api} from './api';
import {Badge,Empty,ErrorMessage,JsonView,Section} from './common';
import {CandleChart} from './Charts';
import {format,sortItems,type Sort} from './model';
import {useDisplayTime} from './Timezone';
import type {Bar,Data,Envelope,Snapshot} from './types';

const columns=[['symbol','Инструмент'],['timeframe','TF'],['direction','Направление'],['setup_combination','Сетапы'],['action','ACTION'],['entry_quality','EQ'],['score','Score сигнала'],['score_long','Score L'],['score_short','Score S'],['price','Цена'],['entry','Entry'],['sl','SL'],['managed_sl','SL / BE'],['tp1','TP1'],['tp2','TP2'],['tp3','TP3'],['tp4','TP4'],['liquidity_target','LIQ'],['rr_liquidity','RR LIQ'],['position_usdt','Позиция USDT'],['risk_usdt','Риск USDT'],['move_r','Δ Entry, R'],['signal_age','Возраст, бары'],['volume_ratio','Volume ×'],['adx','ADX'],['htf_state','HTF'],['mid_state','Trend'],['btc_state','BTC'],['compression','Compression'],['broke_enabled','Broke ON'],['broke_quality_pass','Broke quality'],['data_health','Данные'],['event_time','Обновлено']] as const;
const prices=new Set(['price','entry','sl','managed_sl','tp1','tp2','tp3','tp4','liquidity_target']);
export function WTSetups(){
 const {timestamp}=useDisplayTime();const [params]=useSearchParams();
 const [source,setSource]=useState('engine'),[search,setSearch]=useState(params.get('symbol')??''),[active,setActive]=useState(false),[direction,setDirection]=useState(''),[setup,setSetup]=useState(''),[minimum,setMinimum]=useState(''),[sort,setSort]=useState<Sort[]>([{key:'entry_quality',direction:'desc'}]),[selected,setSelected]=useState<Snapshot|null>(null);
 const query=useQuery({queryKey:['wt-setups',source],queryFn:()=>api<Envelope<Snapshot>>(`/api/wt/setups?signal_source=${source}`),refetchInterval:15000});
 const events=useQuery({queryKey:['wt-events',selected?.symbol,source],queryFn:()=>api<Envelope<Data>>(`/api/wt/events?signal_source=${source}${selected?'&symbol='+encodeURIComponent(selected.symbol):''}&limit=100`),refetchInterval:15000});
 const bars=useQuery({queryKey:['wt-shared-bars',selected?.exchange,selected?.symbol,selected?.timeframe],enabled:!!selected,queryFn:()=>api<Envelope<Bar>>(`/api/setups/${encodeURIComponent(selected!.symbol)}/${selected!.timeframe}/bars?exchange=${selected!.exchange}&limit=300`),refetchInterval:15000});
 const items=useMemo(()=>sortItems((query.data?.items??[]).filter(r=>(!search||r.symbol.toLowerCase().includes(search.toLowerCase()))&&(!direction||r.direction===direction)&&(!setup||Array.isArray(r.setups)&&r.setups.includes(setup))&&(!active||r.action==='ENTER NOW'||r.action==='WAIT RETEST')&&(!minimum||typeof r.entry_quality==='number'&&r.entry_quality>=Number(minimum))),sort),[query.data,search,direction,setup,active,minimum,sort]);
 const current=selected?(query.data?.items.find(r=>r.symbol===selected.symbol&&r.exchange===selected.exchange&&r.timeframe===selected.timeframe)??selected):undefined;
 return <><div className="page-heading"><div><p className="eyebrow">WEIGHTED TRADING · 1.6.4</p><h1>WT_SETUPS <span className="count">{items.length}</span></h1><p>T1 EMA · T2 Breakout · T3 SMC / Liquidity · T4 Momentum</p></div></div>
 <div className="toolbar"><label>Источник<select value={source} onChange={e=>{setSource(e.target.value);setSelected(null);}}><option value="engine">Расчет системы</option><option value="tradingview">Сигналы TradingView</option></select></label><label>Инструмент<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск…"/></label><select aria-label="Направление WT" value={direction} onChange={e=>setDirection(e.target.value)}><option value="">Все направления</option><option>LONG</option><option>SHORT</option></select><select aria-label="Тип WT" value={setup} onChange={e=>setSetup(e.target.value)}><option value="">Все T1–T4</option>{['T1','T2','T3','T4'].map(t=><option key={t}>{t}</option>)}</select><label>EQ ≥<input type="number" min="0" max="100" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><label className="inline"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>ENTER NOW / WAIT RETEST</label></div>
 <p className="subtle">Свечи и рыночные подключения общие с BROKE_SETUPS. {source==='engine'?'Рассчитываются формулы исходного WT; parity с TradingView пока не подтверждена.':'Показаны последние полученные сообщения, а не текущая рыночная оценка. Поля, отсутствующие в сообщении, обозначены н/д.'} T1–T4 — стратегии; TP1–TP4 — цели цены.</p>
 <ErrorMessage error={query.error}/><div className="table-scroll"><table className="screener"><thead><tr>{columns.map(([key,label])=><th key={key}><button onClick={e=>setSort(old=>{const next:Sort={key,direction:old.find(x=>x.key===key)?.direction==='desc'?'asc':'desc'};return e.shiftKey?[...old.filter(x=>x.key!==key),next]:[next];})}>{label}{sort[0]?.key===key?(sort[0].direction==='desc'?' ↓':' ↑'):''}</button></th>)}</tr></thead><tbody>{items.map(r=><tr key={`${r.exchange}/${r.symbol}/${r.timeframe}`}>{columns.map(([key])=><td key={key}>{key==='symbol'?<button className="symbol" onClick={()=>setSelected(r)}>{r.symbol}<small>{r.exchange}</small></button>:key==='event_time'?timestamp(r[key]):key==='direction'?<Badge tone={r.direction==='LONG'?'good':r.direction==='SHORT'?'bad':'neutral'}>{format(r.direction)}</Badge>:format(r[key],prices.has(key)?8:2)}</td>)}</tr>)}</tbody></table></div>
 {!items.length&&<Empty>{query.isPending?'Загрузка WT…':'Нет состояний по выбранным условиям. Расчет появляется после прогрева общего потока; TradingView — после первого webhook.'}</Empty>}
 {current&&<Section title={`${current.symbol} · WT · общие свечи`}><button onClick={()=>setSelected(null)}>Закрыть</button><ErrorMessage error={bars.error}/><CandleChart bars={bars.data?.items??[]} snapshot={{...current,t1:typeof current.tp1==='number'?current.tp1:undefined}} events={[]}/><details><summary>Атрибуты WT</summary><JsonView data={current}/></details></Section>}
 <Section title={source==='tradingview'?'WT · входящие сигналы TradingView':'WT · история сигналов и состояний'}><p>Хранение — 30 дней. Входящие TradingView T1–T4 автоматически отправляются в настроенный Telegram-чат. Правила Alerts для WT настраиваются отдельно.</p><ErrorMessage error={events.error}/><div className="table-scroll"><table><thead><tr><th>Время</th><th>Инструмент</th><th>Сигналы</th><th>ACTION</th><th>Данные</th></tr></thead><tbody>{events.data?.items.map((r,i)=><tr key={String(r.id??i)}><td>{timestamp(r.received_at??r.event_time)}</td><td>{format(r.symbol)} · {format(r.direction)}</td><td>{format(r.signals)}</td><td>{format(r.action)}</td><td><details><summary>{r.duplicate_of?'Повтор доставки':'Подробности'}</summary><JsonView data={r}/></details></td></tr>)}</tbody></table></div></Section></>;
}
